# ---
# simulation:
#     seed: 42
#     n_samples: 2_048
#     kernel_dim: 0                   # bases of null(f) to construct DA. Set to 0 or -1 for random or full respectively.
#     n_experiments: 1
#     sweep_samples: 32
#     methods:
#         - ATE
#         - ERM
#         - DA+ERM
#         - DA+IV
#         - PI_INV
#         - PI
#         - DA+PI
#         - DA+PI_IV
#     sweep_mode: query
#     metric: worst_error     # Options: approximation_error, worst_error, interval_width
#     augmentation: translate
#     plot_panel: true

optical_device:
    seed: 69
    n_samples: 1_000
    n_experiments: 8
    sweep_samples: 32
    methods:
        - ATE
        - ERM
        - DA+ERM
        - DA+IV
        - PI_INV
        - PI
        - DA+PI
        - DA+PI_IV
    sweep_mode: query
    metric: worst_error
    # augmentation: all
    augmentation: rotation > hflip > vflip > gaussian-noise
    # augmentation: rotation > hflip > vflip > random-permutation
    plot_panel: true

# colored_mnist:
#     seed: 42
#     num_seeds: 10
#     n_samples: 60_000
#     methods:
#         - ATE
#         - ERM
#         - DA+ERM
#         - DA+IV
#         - PI_INV
#         - PI
#         - DA+PI
#         - DA+PI_IV
#     sweep_mode: query
#     metric: approximation_error
#     augmentation: jitter > translate
#     plot_panel: true

hyperparameters:
    lr: 0.01            # learning rate for stochastic gradient descent
    batch: 256          # batch size
    epochs: 16          # number of epochs
    n_jobs: -1           # number of queries to run in parallel