########################################
#
#  Linear Gaussian SEM
#
########################################

import numpy as np
from typing import Optional, Tuple
from numpy.typing import NDArray

from src.sem.abstract import StructuralEquationModel as SEM


OUTCOME_DIMENSION: int = 1
TREATMENT_DIMENSION: int = 32


class LinearSimulationSEM(SEM):
    """
    SEM:
        X ~ N(0, I)
        xi = kappa * e^T X + sqrt(1 - kappa^2) * eps
        Y = f^T X + xi

    Confounding is set by the true budget `gamma` (paper's calibrated gamma,
    i.e. bias^2/sigma^2), internally kappa = sqrt(gamma / (1 + gamma)).
    `gamma=None` means kappa=1 (fully confounded, sigma^2=0, gamma=inf).
    """

    def __init__(
        self,
        outcome_dimension: int = OUTCOME_DIMENSION,
        treatment_dimension: int = TREATMENT_DIMENSION,
        gamma: Optional[float] = None,
    ):
        self.outcome_dimension = outcome_dimension
        self.treatment_dimension = treatment_dimension

        # Confounding direction W_XXi ~ N(0, I), normalized
        W_XXi = np.random.randn(treatment_dimension)
        self.W_XXi = W_XXi / np.linalg.norm(W_XXi)

        # Structural coefficients f ~ N(0, I)
        self.W_XY = np.random.randn(
            treatment_dimension, outcome_dimension
        )

        self.gamma = gamma
        super().__init__()

    # ---------------------------------------------------------- confounding

    @property
    def gamma(self) -> Optional[float]:
        """True (calibrated) confounding budget; None = inf."""
        return self._gamma

    @gamma.setter
    def gamma(self, gamma: Optional[float]):
        if gamma is not None:
            assert gamma >= 0.0, '`gamma` must be non-negative.'
        self._gamma = gamma

    @property
    def kappa(self) -> float:
        """Confounding strength kappa = sqrt(gamma / (1 + gamma)) in [0, 1]."""
        if self._gamma is None:
            return 1.0
        return float(np.sqrt(self._gamma / (1.0 + self._gamma)))

    @property
    def bias_sq(self) -> float:
        return self.kappa ** 2

    @property
    def sigma_sq(self) -> float:
        return 1.0 - self.kappa ** 2

    # -------------------------------------------------------------- sampling

    def sample(
        self,
        N: int = 1,
        gamma: Optional[float] = None,
        intervention: bool = False,
        **kwargs
    ) -> Tuple[NDArray, NDArray]:
        if gamma is not None:
            self.gamma = gamma
        kappa = self.kappa

        # 1. Sample the underlying treatment X
        X = np.random.randn(N, self.treatment_dimension)

        # 2. Sample the independent error eps
        eps = np.random.randn(N, self.outcome_dimension)

        if intervention:
            # do(X): the "true" xi must be independent of the intervened X.
            # Sample a phantom X_confound for the xi that 'would have' happened.
            X_confound = np.random.randn(N, self.treatment_dimension)
            xi = (kappa * (X_confound @ self.W_XXi).reshape(-1, 1)
                  + np.sqrt(1 - kappa**2) * eps)
        else:
            # Observational: xi is explicitly tied to X
            xi = (kappa * (X @ self.W_XXi).reshape(-1, 1)
                  + np.sqrt(1 - kappa**2) * eps)

        # 3. Y is generated by the invariant f + the confounding xi
        Y = X @ self.W_XY + xi + 0.1 * np.random.randn(N, self.outcome_dimension)

        return X, Y
