########################################
#
#  Linear Gaussian SEM
#
########################################


import numpy as np
from numpy.typing import NDArray

from src.sem.abstract import StructuralEquationModel as SEM

OUTCOME_DIMENSION: int = 1
TREATMENT_DIMENSION: int = 32
OUTCOME_NOISE_STD: float = 0.1  # s: unconfoundable outcome noise
MAX_GAMMA: float = 1.0 / OUTCOME_NOISE_STD**2


class LinearSimulationSEM(SEM):
    """
    SEM:
        X ~ N(0, I)
        xi = kappa * e^T X + sqrt(1 - kappa^2) * eps
        Y = f^T X + xi + s * nu

    Confounding is set by the true budget `gamma` (paper's calibrated gamma,
    i.e. bias^2/sigma^2 = kappa^2 / (1 - kappa^2 + s^2)), inverted as
    kappa^2 = gamma (1 + s^2) / (1 + gamma) so that gamma* == gamma exactly.
    `gamma=None` means kappa=1 (fully confounded, sigma^2 = s^2, gamma = 1/s^2).
    """

    def __init__(
        self,
        outcome_dimension: int = OUTCOME_DIMENSION,
        treatment_dimension: int = TREATMENT_DIMENSION,
        gamma: float | None = None,
    ):
        self.outcome_dimension = outcome_dimension
        self.treatment_dimension = treatment_dimension

        # Confounding direction W_XXi ~ N(0, I), normalized
        W_XXi = np.random.randn(treatment_dimension)
        self.W_XXi = W_XXi / np.linalg.norm(W_XXi)

        # Structural coefficients f ~ N(0, I)
        self.W_XY = np.random.randn(treatment_dimension, outcome_dimension)

        self.gamma = gamma
        super().__init__()

    # ---------------------------------------------------------- confounding

    @property
    def gamma(self) -> float | None:
        """True (calibrated) confounding budget; None = inf."""
        return self._gamma

    @gamma.setter
    def gamma(self, gamma: float | None):
        if gamma is not None:
            if gamma < 0.0:
                raise ValueError("`gamma` must be non-negative.")
            if gamma > MAX_GAMMA:
                raise ValueError(f"`gamma` must be <= 1/s^2 = {MAX_GAMMA}.")
        self._gamma = gamma

    @property
    def kappa(self) -> float:
        """kappa^2 = gamma (1 + s^2) / (1 + gamma), in [0, 1]."""
        if self._gamma is None:
            return 1.0
        s_sq = OUTCOME_NOISE_STD**2
        kappa_sq = self._gamma * (1.0 + s_sq) / (1.0 + self._gamma)
        return float(np.sqrt(min(kappa_sq, 1.0)))  # guard gamma == MAX_GAMMA

    @property
    def bias_sq(self) -> float:
        return self.kappa**2

    @property
    def sigma_sq(self) -> float:
        return 1.0 - self.kappa**2 + OUTCOME_NOISE_STD**2

    # -------------------------------------------------------------- sampling

    def sample(
        self, N: int = 1, gamma: float | None = None, intervention: bool = False, **kwargs
    ) -> tuple[NDArray, NDArray]:
        if gamma is not None:
            self.gamma = gamma
        kappa = self.kappa

        # 1. Sample the underlying treatment X
        X = np.random.randn(N, self.treatment_dimension)

        # 2. Sample the independent error eps
        eps = np.random.randn(N, self.outcome_dimension)

        if intervention:
            # do(X): the "true" xi must be independent of the intervened X.
            # Sample a phantom X_confound for the xi that 'would have' happened.
            X_confound = np.random.randn(N, self.treatment_dimension)
            xi = kappa * (X_confound @ self.W_XXi).reshape(-1, 1) + np.sqrt(1 - kappa**2) * eps
        else:
            # Observational: xi is explicitly tied to X
            xi = kappa * (X @ self.W_XXi).reshape(-1, 1) + np.sqrt(1 - kappa**2) * eps

        # 3. Y is generated by the invariant f + the confounding xi + noise
        Y = X @ self.W_XY + xi + OUTCOME_NOISE_STD * np.random.randn(N, self.outcome_dimension)

        return X, Y
